-- MySQL Script generated by MySQL Workbench
-- Sun Oct  7 19:55:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trabbd3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabbd3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabbd3` DEFAULT CHARACTER SET utf8 ;
USE `trabbd3` ;

-- -----------------------------------------------------
-- Table `trabbd3`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nomePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` VARCHAR(45) NOT NULL,
  `pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_estado_pais1_idx` (`pais_idPais` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_idPais`)
    REFERENCES `trabbd3`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(45) NOT NULL,
  `estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_cidade_estado1_idx` (`estado_idEstado` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `trabbd3`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`bairro` (
  `idBairro` INT NOT NULL AUTO_INCREMENT,
  `nomeBairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBairro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`rua` (
  `idRua` INT NOT NULL AUTO_INCREMENT,
  `nomeRua` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRua`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cidade_idCidade` INT NOT NULL,
  `bairro_idBairro` INT NOT NULL,
  `rua_idRua` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_enderecoCliente_cidade1_idx` (`cidade_idCidade` ASC),
  INDEX `fk_enderecoCliente_bairro1_idx` (`bairro_idBairro` ASC),
  INDEX `fk_enderecoCliente_rua1_idx` (`rua_idRua` ASC),
  CONSTRAINT `fk_enderecoCliente_cidade1`
    FOREIGN KEY (`cidade_idCidade`)
    REFERENCES `trabbd3`.`cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecoCliente_bairro1`
    FOREIGN KEY (`bairro_idBairro`)
    REFERENCES `trabbd3`.`bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecoCliente_rua1`
    FOREIGN KEY (`rua_idRua`)
    REFERENCES `trabbd3`.`rua` (`idRua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`enderecoEspecifico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`enderecoEspecifico` (
  `idEnderecoEspecifico` INT NOT NULL,
  `numeroEndereco` VARCHAR(45) NOT NULL,
  `cepEndereco` VARCHAR(20) NOT NULL,
  `complementoEndereco` TEXT NULL,
  `endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idEnderecoEspecifico`),
  INDEX `fk_enderecoEspecifico_endereco1_idx` (`endereco_idEndereco` ASC),
  CONSTRAINT `fk_enderecoEspecifico_endereco1`
    FOREIGN KEY (`endereco_idEndereco`)
    REFERENCES `trabbd3`.`endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `cpfCliente` VARCHAR(14) NOT NULL,
  `rgCliente` VARCHAR(20) NOT NULL,
  `enderecoEspecifico_idEnderecoEspecifico` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idCliente` ASC),
  INDEX `fk_cliente_enderecoEspecifico1_idx` (`enderecoEspecifico_idEnderecoEspecifico` ASC),
  CONSTRAINT `fk_cliente_enderecoEspecifico1`
    FOREIGN KEY (`enderecoEspecifico_idEnderecoEspecifico`)
    REFERENCES `trabbd3`.`enderecoEspecifico` (`idEnderecoEspecifico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`hotel` (
  `idHotel` INT NOT NULL AUTO_INCREMENT,
  `nomeHotel` VARCHAR(45) NOT NULL,
  `cnpjHotel` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idHotel`),
  UNIQUE INDEX `idHotel_UNIQUE` (`idHotel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`telefoneCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`telefoneCliente` (
  `idTelefoneCliente` INT NOT NULL AUTO_INCREMENT,
  `telefoneCliente` VARCHAR(20) NOT NULL,
  `telefoneCliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idTelefoneCliente`),
  UNIQUE INDEX `idTelefoneCliente_UNIQUE` (`idTelefoneCliente` ASC),
  INDEX `fk_telefoneCliente_cliente_idx` (`telefoneCliente_idCliente` ASC),
  CONSTRAINT `fk_telefoneCliente_cliente`
    FOREIGN KEY (`telefoneCliente_idCliente`)
    REFERENCES `trabbd3`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`telefoneHotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`telefoneHotel` (
  `idTelefoneHotel` INT NOT NULL AUTO_INCREMENT,
  `telefoneHotel` VARCHAR(20) NOT NULL,
  `hotel_idHotel` INT NOT NULL,
  PRIMARY KEY (`idTelefoneHotel`),
  UNIQUE INDEX `idTelefoneCliente_UNIQUE` (`idTelefoneHotel` ASC),
  INDEX `fk_telefoneHotel_hotel1_idx` (`hotel_idHotel` ASC),
  CONSTRAINT `fk_telefoneHotel_hotel1`
    FOREIGN KEY (`hotel_idHotel`)
    REFERENCES `trabbd3`.`hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`emailCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`emailCliente` (
  `idEmailCliente` INT NOT NULL AUTO_INCREMENT,
  `emailCliente` VARCHAR(45) NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEmailCliente`),
  UNIQUE INDEX `idEmailCliente_UNIQUE` (`idEmailCliente` ASC),
  INDEX `fk_emailCliente_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_emailCliente_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `trabbd3`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`emailHotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`emailHotel` (
  `idEmailHotel` INT NOT NULL AUTO_INCREMENT,
  `emailHotel` VARCHAR(45) NOT NULL,
  `hotel_idHotel` INT NOT NULL,
  PRIMARY KEY (`idEmailHotel`),
  UNIQUE INDEX `idEmailCliente_UNIQUE` (`idEmailHotel` ASC),
  INDEX `fk_emailHotel_hotel1_idx` (`hotel_idHotel` ASC),
  CONSTRAINT `fk_emailHotel_hotel1`
    FOREIGN KEY (`hotel_idHotel`)
    REFERENCES `trabbd3`.`hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`passeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`passeio` (
  `idPasseio` INT NOT NULL AUTO_INCREMENT,
  `nomePasseio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPasseio`),
  UNIQUE INDEX `idPasseio_UNIQUE` (`idPasseio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`ciaAerea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`ciaAerea` (
  `idCiaAerea` INT NOT NULL AUTO_INCREMENT,
  `nomeCiaArea` VARCHAR(45) NOT NULL,
  `cnpjCiaAerea` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCiaAerea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`passagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`passagem` (
  `idPassagem` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataPassagem` VARCHAR(10) NOT NULL,
  `horarioPassagem` VARCHAR(8) NOT NULL,
  `somenteIda` TINYINT NOT NULL,
  `assento` VARCHAR(15) NOT NULL,
  `ciaAerea_idCiaAerea` INT NOT NULL,
  `cidadeOrigem` INT NOT NULL,
  `cidadeDestino` INT NOT NULL,
  PRIMARY KEY (`idPassagem`),
  INDEX `fk_passagem_ciaAerea1_idx` (`ciaAerea_idCiaAerea` ASC),
  INDEX `fk_passagem_cidade1_idx` (`cidadeOrigem` ASC),
  INDEX `fk_passagem_cidade2_idx` (`cidadeDestino` ASC),
  CONSTRAINT `fk_passagem_ciaAerea1`
    FOREIGN KEY (`ciaAerea_idCiaAerea`)
    REFERENCES `trabbd3`.`ciaAerea` (`idCiaAerea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passagem_cidade1`
    FOREIGN KEY (`cidadeOrigem`)
    REFERENCES `trabbd3`.`cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passagem_cidade2`
    FOREIGN KEY (`cidadeDestino`)
    REFERENCES `trabbd3`.`cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`clienteHotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`clienteHotel` (
  `cliente_idCliente` INT NOT NULL,
  `hotel_idHotel` INT NOT NULL,
  `dataInicioReserva` VARCHAR(10) NOT NULL,
  `dataFinalReserva` VARCHAR(10) NOT NULL,
  `precoHotel` FLOAT NOT NULL,
  PRIMARY KEY (`cliente_idCliente`, `hotel_idHotel`, `dataInicioReserva`, `dataFinalReserva`),
  INDEX `fk_cliente_has_hotel_hotel1_idx` (`hotel_idHotel` ASC),
  INDEX `fk_cliente_has_hotel_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_cliente_has_hotel_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `trabbd3`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_hotel_hotel1`
    FOREIGN KEY (`hotel_idHotel`)
    REFERENCES `trabbd3`.`hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`clientePasseio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`clientePasseio` (
  `cliente_idCliente` INT NOT NULL,
  `passeio_idPasseio` INT NOT NULL,
  `dataPasseio` VARCHAR(10) NOT NULL,
  `precoPasseio` FLOAT NOT NULL,
  PRIMARY KEY (`cliente_idCliente`, `passeio_idPasseio`, `dataPasseio`),
  INDEX `fk_cliente_has_passeio_passeio1_idx` (`passeio_idPasseio` ASC),
  INDEX `fk_cliente_has_passeio_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_cliente_has_passeio_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `trabbd3`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_passeio_passeio1`
    FOREIGN KEY (`passeio_idPasseio`)
    REFERENCES `trabbd3`.`passeio` (`idPasseio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`clientePassagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`clientePassagem` (
  `cliente_idCliente` INT NOT NULL,
  `passagem_idPassagem` INT UNSIGNED NOT NULL,
  `precoPassagem` FLOAT NOT NULL,
  PRIMARY KEY (`cliente_idCliente`, `passagem_idPassagem`),
  INDEX `fk_cliente_has_passagem_passagem1_idx` (`passagem_idPassagem` ASC),
  INDEX `fk_cliente_has_passagem_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_cliente_has_passagem_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `trabbd3`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_passagem_passagem1`
    FOREIGN KEY (`passagem_idPassagem`)
    REFERENCES `trabbd3`.`passagem` (`idPassagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabbd3`.`hotelEnderecoEspecifico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabbd3`.`hotelEnderecoEspecifico` (
  `hotel_idHotel` INT NOT NULL,
  `enderecoEspecifico_idEnderecoEspecifico` INT NOT NULL,
  PRIMARY KEY (`hotel_idHotel`, `enderecoEspecifico_idEnderecoEspecifico`),
  INDEX `fk_hotel_has_enderecoEspecifico_enderecoEspecifico1_idx` (`enderecoEspecifico_idEnderecoEspecifico` ASC),
  INDEX `fk_hotel_has_enderecoEspecifico_hotel1_idx` (`hotel_idHotel` ASC),
  CONSTRAINT `fk_hotel_has_enderecoEspecifico_hotel1`
    FOREIGN KEY (`hotel_idHotel`)
    REFERENCES `trabbd3`.`hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_has_enderecoEspecifico_enderecoEspecifico1`
    FOREIGN KEY (`enderecoEspecifico_idEnderecoEspecifico`)
    REFERENCES `trabbd3`.`enderecoEspecifico` (`idEnderecoEspecifico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
